# Generated by Django 3.2.9 on 2021-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20211110_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
