# Generated by Django 3.2.9 on 2021-11-11 21:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_alter_document_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='url',
            new_name='download_url',
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('user', 'download_url')},
        ),
    ]
